//
// Created by ganymed on 30/03/16.
//

#ifndef PINMAPPINGS_H
#define PINMAPPINGS_H

#include <avr/io.h>


/*      External Interrupt      */

#define EXTERNAL_INTERRUPT_PORT_REGISTER PORTD
#define EXTERNAL_INTERRUPT_0_PORT_PIN PORTD2
#define EXTERNAL_INTERRUPT_1_PORT_PIN PORTD3

#define EXTERNAL_INTERRUPT_DDR_REGISTER DDRD
#define EXTERNAL_INTERRUPT_0_DDR_PIN DDD2
#define EXTERNAL_INTERRUPT_1_DDR_PIN DDD3


/*      Pin Change Interrupt      */

#define REGISTER_B_PIN_REGISTER PINB
#define REGISTER_B_PORT_REGISTER PORTB

#define REGISTER_C_PIN_REGISTER PINC
#define REGISTER_C_PORT_REGISTER PORTC

#define REGISTER_D_PIN_REGISTER PIND
#define REGISTER_D_PORT_REGISTER PORTD

#define PIN_CHANGE_INTERRUPT_PIN PCINT8
#define PIN_CHANGE_INTERRUPT_1_PORT_PIN PORTC0


#endif //PINMAPPINGS_H
