//
// Created by ganymed on 30/03/16.
//

#ifndef PINMAPPINGS_H
#define PINMAPPINGS_H

#include <avr/io.h>


/*      External Interrupt      */

#define EXTERNAL_INTERRUPT_PORT_REGISTER PORTD
#define EXTERNAL_INTERRUPT_0_PORT_PIN PORTD2
#define EXTERNAL_INTERRUPT_1_PORT_PIN PORTD3

#define EXTERNAL_INTERRUPT_DDR_REGISTER DDRD
#define EXTERNAL_INTERRUPT_0_DDR_PIN DDD2
#define EXTERNAL_INTERRUPT_1_DDR_PIN DDD3


/*      Pin Change Interrupt      */

#define REGISTER_B_PIN_REGISTER PINB
#define REGISTER_B_PORT_REGISTER PORTB

#define REGISTER_C_PIN_REGISTER PINC
#define REGISTER_C_PORT_REGISTER PORTC

#define REGISTER_D_PIN_REGISTER PIND
#define REGISTER_D_PORT_REGISTER PORTD

#define PIN_CHANGE_INTERRUPT_PIN PCINT8
#define PIN_CHANGE_INTERRUPT_1_PORT_PIN PORTC0



/*      Shift Register      */

#define SHIFT_REGISTER_DATA_OUT_PIN PINB2
#define SHIFT_REGISTER_DATA_OUT_PORT PORTB
#define SHIFT_REGISTER_DATA_OUT_DDR DDRB
#define SHIFT_REGISTER_DATA_OUT_DDR_PIN DDB2

#define SHIFT_REGISTER_SHIFT_CLOCK_PIN PINB1
#define SHIFT_REGISTER_SHIFT_CLOCK_PORT PORTB
#define SHIFT_REGISTER_SHIFT_CLOCK_DDR DDRB
#define SHIFT_REGISTER_SHIFT_CLOCK_DDR_PIN DDB1

#define SHIFT_REGISTER_STORAGE_CLOCK_PIN PINB0
#define SHIFT_REGISTER_STORAGE_CLOCK_PORT PORTB
#define SHIFT_REGISTER_STORAGE_CLOCK_DDR DDRB
#define SHIFT_REGISTER_STORAGE_CLOCK_DDR_PIN DDB0


/*      7 Segment       */

#define LED_A_PIN PIND2
#define LED_A_PORT PORTD
#define LED_A_DDR DDRD
#define LED_A_DDR_PIN DDD2

#define LED_B_PIN PIND3
#define LED_B_PORT PORTD
#define LED_B_DDR DDRD
#define LED_B_DDR_PIN DDD3

#define LED_C_PIN PIND4
#define LED_C_PORT PORTD
#define LED_C_DDR DDRD
#define LED_C_DDR_PIN DDD4

#define LED_D_PIN PIND5
#define LED_D_PORT PORTD
#define LED_D_DDR DDRD
#define LED_D_DDR_PIN DDD5

#define LED_E_PIN PIND6
#define LED_E_PORT PORTD
#define LED_E_DDR DDRD
#define LED_E_DDR_PIN DDD6

#define LED_F_PIN PIND7
#define LED_F_PORT PORTD
#define LED_F_DDR DDRD
#define LED_F_DDR_PIN DDD7

#define LED_G_PIN PINB0
#define LED_G_PORT PORTB
#define LED_G_DDR DDRB
#define LED_G_DDR_PIN DDB0


#endif //PINMAPPINGS_H
