//
// Created by ganymed on 30/03/16.
//

#ifndef PINMAPPINGS_H
#define PINMAPPINGS_H

#include <avr/io.h>


/*      External Interrupt      */

#define EXTERNAL_INTERRUPT_PORT_REGISTER PORTD
#define EXTERNAL_INTERRUPT_0_PORT_PIN PORTD2
#define EXTERNAL_INTERRUPT_1_PORT_PIN PORTD3


/*      Pin Change Interrupt      */

#define PIN_CHANGE_INTERRUPT_PIN PCINT8
#define PIN_CHANGE_INTERRUPT_PIN_REGISTER PINC
#define PIN_CHANGE_INTERRUPT_PORT_REGISTER PORTC
#define PIN_CHANGE_INTERRUPT_1_PORT_PIN PORTC0


#endif //PINMAPPINGS_H
